// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeaderAdvancedSearch: typeof import('./src/components/app/HeaderAdvancedSearch.vue')['default']
    AppHeaderArchive: typeof import('./src/components/app/HeaderArchive.vue')['default']
    AppHeaderBasicSearch: typeof import('./src/components/app/HeaderBasicSearch.vue')['default']
    ArchiveApiSearch: typeof import('./src/views/archive/components/ApiSearch.vue')['default']
    ArchiveApiSearchResult: typeof import('./src/views/archive/components/ApiSearchResult.vue')['default']
    ArchiveArchive: typeof import('./src/views/archive/Archive.vue')['default']
    BaseBaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseBaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseBaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseDbLink: typeof import('./src/components/base/DbLink.vue')['default']
    DatabaseDatabase: typeof import('./src/views/database/Database.vue')['default']
    DatabaseDatabaseInfos: typeof import('./src/views/database/components/DatabaseInfos.vue')['default']
    DatabaseModulesMoviesModulesMovieMovie: typeof import('./src/views/database/modules/movies/modules/movie/Movie.vue')['default']
    DatabaseModulesMoviesMovies: typeof import('./src/views/database/modules/movies/Movies.vue')['default']
    DatabaseModulesSearchAdvancedSearch: typeof import('./src/views/database/modules/search/components/AdvancedSearch.vue')['default']
    DatabaseModulesSearchBasicSearch: typeof import('./src/views/database/modules/search/components/BasicSearch.vue')['default']
    DatabaseModulesSearchSearch: typeof import('./src/views/database/modules/search/Search.vue')['default']
    HomeHome: typeof import('./src/views/home/Home.vue')['default']
    'IconIconoir:arrowDown': typeof import('~icons/iconoir/arrow-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSettings: typeof import('./src/views/settings/Settings.vue')['default']
  }
}

export {}
