// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiApi: typeof import('./src/views/api/Api.vue')['default']
    ApiApiSearch: typeof import('./src/views/api/components/ApiSearch.vue')['default']
    ApiApiSearchResult: typeof import('./src/views/api/components/ApiSearchResult.vue')['default']
    AppHeaderAdvancedSearch: typeof import('./src/components/app/HeaderAdvancedSearch.vue')['default']
    AppHeaderApiSearch: typeof import('./src/components/app/HeaderApiSearch.vue')['default']
    AppHeaderBasicSearch: typeof import('./src/components/app/HeaderBasicSearch.vue')['default']
    BaseBasicButton: typeof import('./src/components/base/BasicButton.vue')['default']
    BaseBasicCheckbox: typeof import('./src/components/base/BasicCheckbox.vue')['default']
    BaseBasicInput: typeof import('./src/components/base/BasicInput.vue')['default']
    BaseBasicModal: typeof import('./src/components/base/BasicModal.vue')['default']
    BaseBasicSelect: typeof import('./src/components/base/BasicSelect.vue')['default']
    BaseBasicTextarea: typeof import('./src/components/base/BasicTextarea.vue')['default']
    BaseIndexLink: typeof import('./src/components/base/IndexLink.vue')['default']
    HomeHome: typeof import('./src/views/home/Home.vue')['default']
    Index: typeof import('./src/views/index/Index.vue')['default']
    IndexIndexInfos: typeof import('./src/views/index/components/IndexInfos.vue')['default']
    IndexModulesMoviesDisplayMovie: typeof import('./src/views/index/modules/movies/components/DisplayMovie.vue')['default']
    IndexModulesMoviesMovieCast: typeof import('./src/views/index/modules/movies/components/MovieCast.vue')['default']
    IndexModulesMoviesMovieCrewAdditional: typeof import('./src/views/index/modules/movies/components/MovieCrewAdditional.vue')['default']
    IndexModulesMoviesMovieCrewMain: typeof import('./src/views/index/modules/movies/components/MovieCrewMain.vue')['default']
    IndexModulesMoviesMovieInfoItem: typeof import('./src/views/index/modules/movies/components/MovieInfoItem.vue')['default']
    IndexModulesMoviesMovieInfoList: typeof import('./src/views/index/modules/movies/components/MovieInfoList.vue')['default']
    IndexModulesMoviesMovieInfos: typeof import('./src/views/index/modules/movies/components/MovieInfos.vue')['default']
    IndexModulesMoviesMovieKeywords: typeof import('./src/views/index/modules/movies/components/MovieKeywords.vue')['default']
    IndexModulesMoviesMoviePoster: typeof import('./src/views/index/modules/movies/components/MoviePoster.vue')['default']
    IndexModulesMoviesMovies: typeof import('./src/views/index/modules/movies/Movies.vue')['default']
    IndexModulesMoviesMovieTrailer: typeof import('./src/views/index/modules/movies/components/MovieTrailer.vue')['default']
    IndexModulesSearchAdvancedSearch: typeof import('./src/views/index/modules/search/components/AdvancedSearch.vue')['default']
    IndexModulesSearchDisplaySearch: typeof import('./src/views/index/modules/search/components/DisplaySearch.vue')['default']
    IndexModulesSearchSearch: typeof import('./src/views/index/modules/search/Search.vue')['default']
    IndexModulesSearchSearchResult: typeof import('./src/views/index/modules/search/components/SearchResult.vue')['default']
    IndexModulesSearchSearchResultDeleteButton: typeof import('./src/views/index/modules/search/components/SearchResultDeleteButton.vue')['default']
    IndexModulesSearchSearchResultDeleteItem: typeof import('./src/views/index/modules/search/components/SearchResultDeleteItem.vue')['default']
    IndexModulesSearchSearchResultEditButton: typeof import('./src/views/index/modules/search/components/SearchResultEditButton.vue')['default']
    IndexModulesSearchSearchResultEditContent: typeof import('./src/views/index/modules/search/components/SearchResultEditContent.vue')['default']
    IndexModulesSearchSearchResults: typeof import('./src/views/index/modules/search/components/SearchResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCreateIndexButton: typeof import('./src/views/settings/components/CreateIndexButton.vue')['default']
    SettingsCreateIndexContent: typeof import('./src/views/settings/components/CreateIndexContent.vue')['default']
    SettingsDeleteIndexButton: typeof import('./src/views/settings/components/DeleteIndexButton.vue')['default']
    SettingsDeleteIndexContent: typeof import('./src/views/settings/components/DeleteIndexContent.vue')['default']
    SettingsEditIndexButton: typeof import('./src/views/settings/components/EditIndexButton.vue')['default']
    SettingsEditIndexContent: typeof import('./src/views/settings/components/EditIndexContent.vue')['default']
    SettingsIndexFolderButton: typeof import('./src/views/settings/components/IndexFolderButton.vue')['default']
    SettingsIndexFolderContent: typeof import('./src/views/settings/components/IndexFolderContent.vue')['default']
    SettingsSelectIndexButton: typeof import('./src/views/settings/components/SelectIndexButton.vue')['default']
    SettingsSettings: typeof import('./src/views/settings/Settings.vue')['default']
  }
}

export {}
