version: "3.9"
services:
  adminer:
    image: adminer:4.8.1
    ports:
      - "8888:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes: 
      - es-data:/usr/share/elasticsearch/data
    env_file:
      - ./app/.env.elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:15.2-alpine3.17
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./app/.env.database
    ports:
      - "5432:5432"

volumes:
  es-data:
  db-data: