def map_imdbApiSchema_to_indexSchema(movie):
    movie_mapped = {
        'title': movie['title'],
        'year': movie['year'],
        'tndbId': movie['id'],
        'imdbId': movie['imdb_id'],
        'originalTitle': movie['original_title'],
        'imageLink': movie['poster_path'],
        'release_date': movie['releaseDate'],
        'runtime': movie['runtime'],
        'budget': movie['budget'],
        'plot': movie['owerview'],
        'homepage': movie['homepage'],
        'directorList': movie['directorList'],
        'writerList': movie['writerList'],
        'starList': movie['starList'],
        'actorList': movie['actorList'],
        'fullCast': movie['fullCast'],
        'genreList': [item['key'] for item in movie['genreList']],
        'countryList': [item['key'] for item in movie['countryList']],
        'languageList': [item['key'] for item in movie['languageList']],
        'contentRating': movie['contentRating'],
        'keywordList': movie['keywordList'],
        'companyList': movie['companyList'],
        'boxOffice': movie['boxOffice'],
        'imdbLink': '/'.join(['https://www.imdb.com/title', movie['id']]),
        'imdbRating': movie['imDbRating'],
        'imdbVotes': movie['imDbRatingVotes'],
        'ratingList': movie['ratings'],
        'wikiLink': movie['wikipedia']['url'],
        'wikiTextShort': movie['wikipedia']['plotShort']['plainText'],
        'wikiTextShortHtml': movie['wikipedia']['plotShort']['html'],
        'wikiTextFull': movie['wikipedia']['plotFull']['plainText'],
        'wikiTextFullHtml': movie['wikipedia']['plotFull']['html'],
        'posterList': movie['posters']['posters'],
        'imageList': movie['images']['items'],
        'trailer': movie['trailer'],
        'tvSeriesInfo': movie['tvSeriesInfo'],
        'tvEpisodeInfo': movie['tvEpisodeInfo'],
        'personalRating': None,
        'personalNotes': None
    }
    if len(movie_mapped['releaseDate']) < 2:
        movie_mapped['releaseDate'] = "2999-12-31"
    return movie_mapped


def getApiKeys():
    return ["id",
            "title",
            "originalTitle",
            "fullTitle",
            "type",
            "year",
            "image",
            "releaseDate",
            "runtimeMins",
            "runtimeStr",
            "plot",
            "plotLocal",
            "plotLocalIsRtl",
            "awards",
            "directors",
            "directorList",
            "writers",
            "writerList",
            "stars",
            "starList",
            "actorList",
            "fullCast",
            "genres",
            "genreList",
            "companies",
            "companyList",
            "countries",
            "countryList",
            "languages",
            "languageList",
            "contentRating",
            "imDbRating",
            "imDbRatingVotes",
            "metacriticRating",
            "ratings",
            "wikipedia",
            "posters",
            "images",
            "trailer",
            "boxOffice",
            "tagline",
            "keywords",
            "keywordList",
            "similars",
            "tvSeriesInfo",
            "tvEpisodeInfo",
            "errorMessage"]